Copy examples and output to readme. Each example must have an associated readme

diff --git a/.github/workflows/run b/.github/workflows/run
--- a/.github/workflows/run
+++ b/.github/workflows/run
@@ -47,11 +47,45 @@ for dir in */ ; do
         echo 'Package and changelog versions do not match!'
         exit 1
     fi
+    # Store readme content for resetting later
+    readme="$(cat README.md)"
     # Install dependencies and run test script
     echo 'Installing dependencies...'
     npm i
     echo 'Running tests...'
     npm test || exit 1
+    # Generate package and run all examples
+    echo 'Generating tarball...'
+    npm pack --pack-destination examples || echo 'Did not pack' # TODO: Fail exit
+    cd examples && {
+        example_file='examples-tmp.md'
+        echo '## Examples' >> "${example_file}"
+        npm i
+        shopt -s nullglob
+        for example in *.js ; do
+            # Save example output to a markdown file
+            echo "Running example ${example}..."
+            {
+                cat "${example}.md" || exit 1
+                echo
+                echo '#### Source'
+                echo '```js'
+                cat "${example}"
+                echo
+                echo '```'
+                echo '#### Output'
+                echo '```text'
+                node "${example}"
+                echo '```'
+            } >> "${example_file}"
+        done
+        # Store the output from the examples and remove the file
+        # Then clean the project and reset the working directory
+        examples="$(cat "${example_file}")"
+        rm "${example_file}"
+        npm run clean
+        cd ..
+    } || echo 'Skipping examples' # TODO: Fail exit
     if "${publish}" ; then
         # Determine latest published version on the registry
         npm_version="$(npm --silent v "${package_name}" version)"
@@ -69,17 +103,19 @@ for dir in */ ; do
             echo "packages['${package_name//"'"/"\\'"}'].ver = '${local_version//"'"/"\\'"}';"
             echo "packages['${package_name//"'"/"\\'"}'].dir = '${dir//"'"/"\\'"}';"
         } >> '../.docs/index.js'
-        # Store current readme content, copy over the
-        # template readme file, and replace variables
+        # Copy over the template readme file and replace variables
         echo 'Generating readme...'
-        readme="$(cat README.md)"
         cp '../.github/workflows/template.md' README.md
         sed -i "s:%NAME%:${package_name//':'/';'}:g" README.md
         sed -i "s:%DESC%:${package_desc//':'/';'}:g" README.md
         sed -i "s:%DIR%:${dir//':'/';'}:g" README.md
         sed -i "s:%VER%:${local_version//':'/';'}:g" README.md
         sed -i "s:%TIME%:${package_date//':'/';'}:g" README.md
-        echo "${readme}" >> README.md
+        # Append the readme content and example outputs at the end
+        {
+            echo "${readme}"
+            echo "${examples}"
+        } >> README.md
         if [[ "${local_version}" == "${npm_version}" ]] ; then
             echo 'Skipping publish step'
         else
@@ -98,5 +134,7 @@ for dir in */ ; do
         # Reset the readme file to its original state
         echo "${readme}" > README.md
     fi
+    # Run cleanup tasks and reset working directory
+    npm run clean
     cd ..
 done
