Even better and comments

diff --git a/.github/workflows/run b/.github/workflows/run
--- a/.github/workflows/run
+++ b/.github/workflows/run
@@ -17,11 +17,14 @@ if [[ "${1}" == 'publish' ]] ; then
         # Check each directory and publish each project
         cd packages || exit 1
         for dir in */ ; do
-            npm --silent v "${dir}" && {
-                cd "${dir}" || exit 1
-                npm publish --provenance || echo "Cannot publish ${dir}"
-                cd ..
-            }
+            # Skip directories that are not an npm project
+            npm --silent v "${dir}" || { echo "${dir} is not an NPM project" && continue ; }
+            # Set working directory to package directory
+            cd "${dir}" || exit 1
+            # Attempt to publish the package, or show a message
+            npm publish --provenance || echo "Cannot publish ${dir}"
+            # Reset the working directory
+            cd ..
         done
     fi
 fi
