Instead of workspaces, just go directory by directory

diff --git a/.github/workflows/run b/.github/workflows/run
--- a/.github/workflows/run
+++ b/.github/workflows/run
@@ -14,6 +14,10 @@ if [[ "${1}" == 'publish' ]] ; then
         exit 1
     else
         npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" || exit 1
-        npm publish --provenance --workspaces || echo 'One or several packages are already published and were skipped.'
+        # Check each directory and publish each project
+        cd packages || exit 1
+        for dir in */ ; do
+            npm --silent v "${dir}" && { npm publish --provenance || echo "Cannot publish ${dir}" ; }
+        done
     fi
 fi
