Force ALL packages to incorporate examples (#73)

diff --git a/.github/workflows/run b/.github/workflows/run
--- a/.github/workflows/run
+++ b/.github/workflows/run
@@ -47,11 +47,60 @@ for dir in */ ; do
         echo 'Package and changelog versions do not match!'
         exit 1
     fi
+    # Store readme content for resetting later
+    readme="$(cat README.md)"
     # Install dependencies and run test script
     echo 'Installing dependencies...'
-    npm i
+    npm i || exit 1
     echo 'Running tests...'
     npm test || exit 1
+    # Generate package and run all examples
+    echo 'Generating tarball...'
+    npm pack --pack-destination examples || exit 1
+    cd examples && {
+        example_file='examples-tmp.md'
+        {
+            echo '## Examples'
+            echo "Here are a few quickstart examples written in JavaScript that showcase some out-of-box features of the \`${package_name}\` package."
+        } >> "${example_file}"
+        npm i || exit 1
+        for example in * ; do
+            if [[ "${example}" =~ ^([0-9]+-([a-zA-Z0-9_-]+))\.([mc]?js)$ ]] ; then
+                # Save example output to a markdown file
+                echo "Running example ${example}..."
+                {
+                    echo "### ${BASH_REMATCH[2]//-/ }"
+                    cat "${BASH_REMATCH[1]}.md" || exit 1
+                    echo
+                    echo '#### Instructions'
+                    echo '1. Copy the source code'
+                    echo '1. Paste into a new file'
+                    echo "1. Save as \`${BASH_REMATCH[2]}.${BASH_REMATCH[3]}\`"
+                    echo '1. Run this command in your terminal'
+                    echo '    ```shell'
+                    echo "    node ${BASH_REMATCH[2]}.${BASH_REMATCH[3]}"
+                    echo '    ```'
+                    echo '#### Source'
+                    echo '```js'
+                    cat "${example}"
+                    echo
+                    echo '```'
+                    echo '#### Output'
+                    echo '```text'
+                    node "${example}" || exit 1
+                    echo '```'
+                } >> "${example_file}"
+            else
+                echo "Skipping file ${example}"
+            fi
+        done
+        # Store the output from the examples and remove the file
+        # Then clean the project and reset the working directory
+        examples="$(cat "${example_file}")"
+        rm "${example_file}"
+        npm run clean || exit 1
+        cd ..
+    } || exit 1
     if "${publish}" ; then
         # Determine latest published version on the registry
         npm_version="$(npm --silent v "${package_name}" version)"
@@ -69,22 +118,24 @@ for dir in */ ; do
             echo "packages['${package_name//"'"/"\\'"}'].ver = '${local_version//"'"/"\\'"}';"
             echo "packages['${package_name//"'"/"\\'"}'].dir = '${dir//"'"/"\\'"}';"
         } >> '../.docs/index.js'
-        # Store current readme content, copy over the
-        # template readme file, and replace variables
+        # Copy over the template readme file and replace variables
         echo 'Generating readme...'
-        readme="$(cat README.md)"
         cp '../.github/workflows/template.md' README.md
         sed -i "s:%NAME%:${package_name//':'/';'}:g" README.md
         sed -i "s:%DESC%:${package_desc//':'/';'}:g" README.md
         sed -i "s:%DIR%:${dir//':'/';'}:g" README.md
         sed -i "s:%VER%:${local_version//':'/';'}:g" README.md
         sed -i "s:%TIME%:${package_date//':'/';'}:g" README.md
-        echo "${readme}" >> README.md
+        # Append the readme content and example outputs at the end
+        {
+            echo "${readme}"
+            echo "${examples}"
+        } >> README.md
         if [[ "${local_version}" == "${npm_version}" ]] ; then
             echo 'Skipping publish step'
         else
             echo 'Publishing...'
-            npm publish
+            npm publish || exit 1
         fi
         # Only add the MathJax script for documentation
         # because in npm, it will show up as plain text
@@ -98,5 +149,7 @@ for dir in */ ; do
         # Reset the readme file to its original state
         echo "${readme}" > README.md
     fi
+    # Run cleanup tasks and reset working directory
+    npm run clean || exit 1
     cd ..
 done
